name: Live deployment Job

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.2'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Create build directory
      run: mkdir -p path/to/build

    - name: Verify build directory
      run: |
        ls -R path/to/build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-artifacts
        path: path/to/build
        if-no-files-found: warn
        retention-days: 7

    - name: Debugging
      run: |
        ls -R path/to/build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: path/to/build

    - name: Building Next.js application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd public_html
          rm -rf tempPortfolio
          mkdir tempPortfolio
          cp -r path/to/build/* tempPortfolio
          ls
